version: "3.9"
services:
    englishhelper:
        build:
            context: .
            dockerfile: Dockerfile
        image: hdcola/englishhelper:latest
        volumes:
            - "/tmp:/data"
        env_file:
            - local.env