version: "3.4"
services:
    englishhelper:
        build:
            context: .
            dockerfile: Dockerfile
        image: hdcola/englishhelper:stable
        volumes:
            - data:/data
        env_file:
            - local.env
volumes:
    data: {}