---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehelper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehelper
  template:
    metadata:
      labels:
        app: ehelper
    spec:
      containers:
        - name: ehelper
          image: hdcola/englishhelper:v0.5.1
          # not listening to any port
          envFrom:
            - secretRef:
                name: ehelper
          volumeMounts:
            - name: ehelper
              mountPath: /data
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: ehelper
          persistentVolumeClaim:
            claimName: ehelper
