name: Build Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build number
        run: |
          echo "build_number=release-${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hdcola/englishhelper:latest
            hdcola/englishhelper:$build_number
      - name: Update default kubernetes deploy version
        run: |
          sed -i -E "s|(image: hdcola/englishhelper:).*|\1$build_number|g" .kustomize/base/deploy.yaml
      - name: Auto commit & push changes
        run: |
          git config --global user.name 'GHA Bot'
          git config --global user.email 'notifications@github.com'
          git commit -am "Automated commit"
          git push