name: Release Docker image wit tag
on:
  push:
    tags:
      - 'v*'
jobs:
  release_with_tag:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hdcola/englishhelper
          tags: |
            type=ref,event=tag
            type=raw,value=stable
      - name: tag to env
        run: |
          BUILD_TAG=$(echo "${{ steps.meta.outputs.tags }}" |grep -E 'v[0-9\.]+' |head -n 1)
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          echo "TAG_BRANCH=$(git branch -r --contains tags/${BUILD_TAG#*:} |grep -v detached |head -n 1)" >> $GITHUB_ENV
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Update deployment version
        run: |
          sed -i -E "s|(image: )hdcola/englishhelper:.*|\1$BUILD_TAG|g" .kustomize/base/deploy.yaml

      - name: Auto commit & push changes
        run: |
          git config --global user.name 'GH Bot'
          git config --global user.email 'notifications@github.com'
          git commit -am "Automated commit"
          git push origin HEAD:${TAG_BRANCH#*origin/}
